# Generated by Django 6.0.3 on 2026-03-30 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='store.orders')),
                ('quantiteis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_quantity', to='store.orders')),
            ],
        ),
    ]
