# Generated by Django 6.0.3 on 2026-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_quantiteis_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prices',
            field=models.IntegerField(),
        ),
    ]
